### ISSUE TITLE
Laminas Mail 2.15 breaks SMTP in Magento 2.4.3

### ISSUE THREAD

**Issue by perfpcs** [laminas/laminas-mail#170] opened 2021-09-23 04:31 UTC
### Bug Report

This new version that fully breaks Magento 2.4.3 SMTP?? 

How can you guys release something like this that fully breaks Magento 2.4.3 SMTP?? I confirmed its this version by rolling back older version and now all mails send again fine.

#### Current behavior

Doimg the SMTP test in Admin this extension causes SMTP on port 465 SSL to time-out. Even though it times out it sends message 1 or 2 of the test emails. Trying to send regular emails of course all failed from contact us page to order confirm, etc.

#### How to reproduce

Try and do the test emails in M 2.4.3. I use Mailgun with the SMTP extension from MagePal. You will see from the test that it immediately times out with the error message. Still message 1 of 2 sends and arrives. Not 2of 2.

#### Expected behavior

Expect the test email to send both test emails and not deliver a timeout on port 465. Again, your older version was installed and works fine. Please fix, This could not have been tested with the latest M 2.4.3.

**Comment by perfpcs** [comment] 2021-09-23 04:53
![image](https://user-images.githubusercontent.com/22109696/134456278-94b158d9-9bb0-4897-85ed-7a19c51f9913.png)

**Comment by perfpcs** [comment] 2021-09-23 04:54
![image](https://user-images.githubusercontent.com/22109696/134456328-ddc98e88-0f00-49d0-a33d-dfdeaa317b10.png)

**Comment by perfpcs** [comment] 2021-09-23 04:55
older version:

![image](https://user-images.githubusercontent.com/22109696/134456500-57d7223f-5b91-42de-9213-4384dddbe8e3.png)

**Comment by Slamdunk** [comment] 2021-09-23 06:09
Duplicate of #168

**Closed as completed by Slamdunk** 2021-09-23 06:09 UTC
Labels: Bug
