### ISSUE TITLE
$this->headers must be an instance of Headers

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#42] opened 2020-01-15 19:49 UTC
If subject is NULL (mail have no subject) I got this exception

> $this->headers must be an instance of Headers

Need to handle NULL subject without error/exception.

---

Originally posted by @r0073rr0r at https://github.com/zendframework/zend-mail/issues/167

**Comment by michalbundyra** [comment] 2020-01-15 19:49
Please provide code and/or unit test to reproduce the error. I tried the following test and it works: 

```php
    public function testAllowMessageWithEmptySubject()
    {
        $message = new Message();
        $message->addTo('matthew@zend.com')
                ->setSender('ralph.schindler@zend.com', 'Ralph Schindler')
                ->setBody('This is only a test.');

        $this->transport->send($message);
    }
``` 

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mail/issues/167#issuecomment-386848965

**Comment by samsonasik** [comment] 2020-08-03 00:41
I am closing it since there is no code/unit test to reproduce the issue.

**Closed by samsonasik** 2020-08-03 00:41 UTC
