### ISSUE TITLE
non-strict validation flag or mode for reading mails from remote server

### ISSUE THREAD

**Issue by victorannunzi** [laminas/laminas-mail#148] opened 2021-04-12 10:42 UTC
Hi, I'm using Laminas Mail for a project and it would be great to be able to set a non strict validation mode for mails. Since I get them from an inbox I have no control over them and get many errors when using `$mail->getMessage($n)`. The errors don't offer many information about what the problem was, all I get is : 
`The input exceeds the allowed length` or `Invalid header value detected` . I'm pretty new to laminas so maybe there is already a way to go around this, but this fixes would help a lot.

**Comment by Slamdunk** [comment] 2021-04-12 10:49
I guess this is duplicate of https://github.com/laminas/laminas-mail/issues/146

**Comment by froschdesign** [comment] 2021-04-12 10:53
And this #64

**Comment by victorannunzi** [comment] 2021-04-12 10:56
@Slamdunk Thank you

**Closed as completed** 2021-04-12 10:57 UTC
Labels: Enhancement

**Comment by glensc** [comment] 2021-04-12 11:54
can you also close https://github.com/laminas/laminas-mail/issues/64 and point to https://github.com/laminas/laminas-mail/issues/146
