### ISSUE TITLE
Update from 2.14.1 to 2.14.2 breaks Magento 2.4 using external SMTP

### ISSUE THREAD

**Issue by n2diving-dgx** [laminas/laminas-mail#168] opened 2021-09-21 15:45 UTC
Upon composer update from 2.14.1 to 2.14.2 (and later 2.15) attempts to send mail via external SMTP server using Magento 2.4 fails with sendmail timeout.   Forcing a composer downgrade back to 2.14.1 resolves the issue.

**Comment by Ocramius** [comment] 2021-09-21 15:47
See #167 - if you can provide a failing test case, I'll gladly merge+release that patch

**Comment by n2diving-dgx** [comment] 2021-09-21 15:48
see  https://github.com/laminas/laminas-mail/pull/167

**Comment by ste80pa** [comment] 2021-09-22 09:54
Hi!

i found that https://github.com/laminas/laminas-mail/blob/2.16.x/src/Protocol/AbstractProtocol.php#L293 does not handle correctly the metadata returned from https://www.php.net/manual/en/function.stream-get-meta-data.php.

i suggest to change the line 293 to

```php
       if (isset($info['timed_out']) && $info['timed_out']) {
```

**Comment by Ocramius** [comment] 2021-09-22 09:57
@ste80pa did you look at #167?

We need a test case, then it can be merged/tagged.

**Comment by flavioamello** [comment] 2021-09-22 12:18
Same issue here on Magento.
Looks like #167 fix the issue, as I did this fix locally and worked.

**Comment by CreativeNative** [comment] 2021-09-22 15:39
I have the same issue. Get a time-out on my smtp. Please provide a fix asap.

**Comment by Ocramius** [comment] 2021-09-22 15:40
@flavioamello @CreativeNative as I already asked above: please provide a failing test case, and then the fix shall be merged + released :-)

**Comment by CreativeNative** [comment] 2021-09-22 16:09
Actually, we don't have time to fix your problems or write tests for your code. I downgraded now to version 2.14.1. This resolves the problem. 
Have a look on your changes and try to get better tests. Laminas is a really awesome framework, but these problems affect a lot of people who trust that your code works. I missed an inquiry, but luckily they contacted me via email and told me that we have an error in our inquiry form. So please check and fix it as soon as possible. Thanks for your hard work, and please don't take that wrong.

**Comment by Ocramius** [comment] 2021-09-22 16:24
> So please check and fix it as soon as possible.

That's really just up to anyone who can investigate the issue - I'm not really sure how to verify it, but it seems like a lot of people in this thread experienced the issue first-hand (and can help + have a "skin in the game"), and the regression precisely happened because of a lack of tests around that code location.

All I can do myself personally is try doing a fix over the next free weekend in 2 week, when/if I find time :-)

**Comment by Ocramius** [comment] 2021-09-22 16:26
> Actually, we don't have time to fix your problems or write tests for your code.

It seems like everyone had time to investigate the problem and complain about it though? There seems to be a deep misunderstanding of how open source works, since this is not "my" problem (I don't use this component myself, at this time), but rather your problem.

Related: https://github.com/github/feedback/discussions/5709

**Comment by CreativeNative** [comment] 2021-09-22 16:41
> It seems like everyone had time to investigate the problem ...

We don't have time to investigate. Our customers have brought this error to our attention and if it has already come this far, something went horrible wrong. This is not a good publicity for Laminas. 

And I don't know if you are a hired developer from the Linux Foundation or a free developer who supports this Framework. So don't get me wrong. I don't blame you.

**Comment by Ocramius** [comment] 2021-09-22 16:43
> This is not a good publicity for Laminas.

There is no publicity, this is an OSS library :O 

What the hell is wrong with you people? When did you start thinking this is a paid support tracker?

Anyway, if the convo continues that way, I'll lock the thread, and will only react to a patch **WITH FAILING TEST CASE BEFORE CHANGES, AND PASSING AFTER CODE CHANGES**.

**Comment by yivi** [comment] 2021-09-22 16:44
@CreativeNative If you find this work created by volunteers (for which you paid exactly zero before using it to earn money with your clients) lacking, just use something else. Or, you could try creating your own. Or you could try helping fixing the issue instead of just berating the maintainers of the FREE library you are profiting from.

**Comment by zepgram** [comment] 2021-09-22 18:27
@CreativeNative, I have the same issue on magento 2.4.1 and we were able to detect it with our functional testing.

![446](https://user-images.githubusercontent.com/16258478/134400690-4e226dd2-b47f-44a0-972a-42b93fe634b7.png)
Dont' blame external package if you are not able to provide quality gates for your clients.

**Comment by teodorpav** [comment] 2021-09-22 23:00
> Hi!
> 
> i found that https://github.com/laminas/laminas-mail/blob/2.16.x/src/Protocol/AbstractProtocol.php#L293 does not handle correctly the metadata returned from https://www.php.net/manual/en/function.stream-get-meta-data.php.
> 
> i suggest to change the line 293 to
> 
> ```
>        if (isset($info['timed_out']) && $info['timed_out']) {
> ```
Works great!!!
Thank you!!!

**Comment by ghost** [comment] 2021-09-23 02:20
> Hi!
> 
> i found that https://github.com/laminas/laminas-mail/blob/2.16.x/src/Protocol/AbstractProtocol.php#L293 does not handle correctly the metadata returned from https://www.php.net/manual/en/function.stream-get-meta-data.php.
> 
> i suggest to change the line 293 to
> 
> ```
>        if (isset($info['timed_out']) && $info['timed_out']) {
> ```

Work for me. Thank you.

**Comment by Slamdunk** [comment] 2021-09-23 07:19
Solved in https://github.com/laminas/laminas-mail/pull/167

**Closed as completed by Slamdunk** 2021-09-23 07:19 UTC
Labels: Bug

**Comment by Ocramius** [comment] 2021-09-23 08:58
Good work, @Slamdunk! :+1:
